---
- name: Site is down
  hosts: all
  gather_facts: false

  tasks:
    - debug:
        msg: "Website is down!"
    
    - name: Replace Website
      copy: 
       remote_src: yes
       src: /tmp/index.html
       dest: /var/www/html/
       mode: '0644'
