- name: Connect and Fetch
  hosts: all
  gather_facts: false
  connection: local
  vars:
    job_data: "{{response.json.Members}}"

  tasks:
    - name: Connect to iDRAC
      ansible.builtin.uri:
        url: "https://100.96.24.131/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/Jobs"
        method: GET
        user: "saksham"
        password: "Dell_123$"
        validate_certs: 0
      register: response

    - name: Extract job IDs
      set_fact:
        job_ids: "{{ job_ids | default([]) + [item['@odata.id'].split('/')[-1]] }}"
      loop: "{{ job_data }}"

    - name: Display job IDs
      debug:
        var: job_ids




# https://100.71.90.193/redfish/v1/Systems/iDRAC.Embedded.1/Storage/Oem/Dell/DellControllers