---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Job Id
      condition: event.payload.message == "list of job"
      action:
        debug:
          msg: "You said, '{{ event.payload.message }}'. Is that what you meant to say?"
