- name: Server
  hosts: idrac
  gather_facts: false
  connection: local

  tasks:
    - name: Power on Server
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ inventory_hostname }}"
        username: "{{ idrac_user }}"
        password: "{{ idrac_password }}"
        validate_certs: false
        reset_type: "GracefulRestart"
      delegate_to: localhost
